listm = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
listm[0] = int(input("請輸入第1個數字:"))
listm[1] = int(input("請輸入第2個數字:"))
listm[2] = int(input("請輸入第3個數字:"))
listm[3] = int(input("請輸入第4個數字:"))
listm[4] = int(input("請輸入第5個數字:"))
listm[5] = int(input("請輸入第6個數字:"))
listm[6] = int(input("請輸入第7個數字:"))
listm[7] = int(input("請輸入第8個數字:"))
listm[8] = int(input("請輸入第9個數字:"))
listm[9] = int(input("請輸入第10個數字:"))
listm.sort()
listm.reverse()
print("最大的3個數字為:", listm[0], ",", listm[1], ",", listm[2])
print("最小的3個數字為:", listm[7], ",", listm[8], ",", listm[9])
